name: "main"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rome:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Restore Node modules from caches
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: v202101131145-${{ hashFiles('yarn.lock') }}

      - name: Run install
        run: pnpm install

      - name: Run Rome linter
        run: pnpm rome:check
        continue-on-error: true

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Publish package
        env:
          GIT_AUTHOR_NAME: ${{ github.event.pusher.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
          GIT_COMMITTER_NAME: ${{ github.event.pusher.name }}
          GIT_COMMITTER_EMAIL: ${{ github.event.pusher.email }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm semantic-release
