name: "main"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rome:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: rome/setup-rome@v0.4
        with:
          version: latest

      - uses: actions/checkout@v2
      - run: rome check .

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Publish package
        env:
          GIT_AUTHOR_NAME: ${{ github.event.pusher.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
          GIT_COMMITTER_NAME: ${{ github.event.pusher.name }}
          GIT_COMMITTER_EMAIL: ${{ github.event.pusher.email }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm semantic-release
